<?php
return array(
	'html_quiz_count_label' => 'フィールド数',
	'html_quiz_count_note' => '',
	'html_quiz_maxfile_size_label' => 'ファイルの最大サイズ',
	'html_quiz_maxfile_size_note' => '',
	'html_quiz_only_image_label' => '画像のみ許可 (jpeg,png,gif)',
	'html_quiz_only_image_note' => '',
	'html_quiz_image_maxwidth_label' => '画像の最大幅',
	'html_quiz_image_maxwidth_note' => '',
	'html_quiz_image_maxheight_label' => '画像の最大高',
	'html_quiz_image_maxheight_note' => '',
	'html_quiz_thumb_size_label' => '添付画像ファイルのサムネイル画像幅',
	'html_quiz_thumb_size_note' => '',
	'html_quiz_lightbox_effect_label' => 'ライトボックス効果を有効にする',
	'html_quiz_lightbox_effect_note' => '',
	'html_quiz_active_label' => '--------------------　フィールド^ を有効にする --------------------',
	'html_quiz_prompt_label' => '質問フォームでの名前:',
	'html_quiz_prompt_default' => 'フィールド^',
	'html_quiz_prompt_note' => '',
	'html_quiz_prompt_error' => '質問フォームでの名前を入力してください。',
	'html_quiz_note_label' => '質問フォームでの説明 - HTML可:',
	'html_quiz_note_note' => '',
	'html_quiz_type_label' => 'タイプ:',
	'html_quiz_type_text' => 'テキストボックス',
	'html_quiz_type_textarea' => 'テキストエリア',
	'html_quiz_type_checkbox' => 'チェックボックス',
	'html_quiz_type_select' => 'セレクトボックス',
	'html_quiz_type_radio' => 'ラジオボタン',
	'html_quiz_type_file' => 'ファイル',
	'html_quiz_type_note' => '',
	'html_quiz_option_label' => 'オプション:',
	'html_quiz_option_default' => '',
	'html_quiz_option_note' => 'テキストエリアの例: 5 (行数)<BR/>チェックボックスの例: オフ==0||オン==1 / いいえ==0||はい==1<BR/>セレクト/ラジオボタンの例: ||ラベル1==値1||ラベル2==値2||ラベル3==値3<BR/>ファイルの例:カンマ(,)で拡張子を連結<BR/>プログラミングの例: @EVAL return \'||ラベル1==値1||ラベル2==値2\';',
	'html_quiz_option_error' => 'テキストエリアの例: 5 (行数)<BR/>チェックボックスの例: オフ==0||オン==1 / いいえ==0||はい==1<BR/>セレクト/ラジオボタンの例: ||ラベル1==値1||ラベル2==値2||ラベル3==値3<BR/>ファイルの例:カンマ(,)で拡張子を連結<BR/>プログラミングの例: @EVAL return \'||ラベル1==値1||ラベル2==値2\';',
	'html_quiz_option_ext_error' => '^ タイプのファイルを指定してください。',
	'html_quiz_attr_label' => '属性:',
	'html_quiz_attr_note' => '入力用タグの属性をHTMLの規則に従って入力します。<BR/>テキストボックスの例: maxlength="20"<BR/>セレクトボックスの例: size="3"',
	'html_quiz_default_label' => 'デフォルト値:',
	'html_quiz_default_default' => '',
	'html_quiz_default_note' => '',
	'html_quiz_form_pos_label' => '質問フォームでの表示位置:',
	'html_quiz_form_pos_top' => '先頭',
	'html_quiz_form_pos_custom' => 'カスタムテキストの下',
	'html_quiz_form_pos_title' => 'タイトルの下',
	'html_quiz_form_pos_category' => 'カテゴリーの下',
	'html_quiz_form_pos_content' => 'コンテンツの下',
	'html_quiz_form_pos_extra' => 'Q2Aの拡張フィールドの下',
	'html_quiz_form_pos_tags' => 'タグの下',
	'html_quiz_form_pos_notify' => '通知の下',
	'html_quiz_form_pos_bottom' => '最後',
	'html_quiz_form_pos_note' => '',
	'html_quiz_display_label' => '質問ページに表示',
	'html_quiz_display_note' => '',
	'html_quiz_label_label' => '質問ページでの名前:',
	'html_quiz_label_default' => 'フィールド^',
	'html_quiz_label_note' => '',
	'html_quiz_label_error' => '質問ページでの名前を入力してください。',
	'html_quiz_page_pos_label' => '質問ページでの表示位置:',
	'html_quiz_page_pos_upper' => 'コンテンツの上',
	'html_quiz_page_pos_inside' => 'コンテンツの中',
	'html_quiz_page_pos_below' => 'コンテンツの下',
	'html_quiz_page_pos_note' => '"コンテンツの中" を選択した場合、質問者がコンテンツの中にタグ( ^ )を含める必要があることを「質問フォームでの説明」で説明します。',
	'html_quiz_hide_blank_label' => '未入力の場合は質問ページに表示しない',
	'html_quiz_hide_blank_note' => '',
	'html_quiz_required_label' => '入力を強制する',
	'html_quiz_required_note' => '',
	'html_quiz_required_message' => '"^" は必須です。<BR/>',
	'html_quiz_save_button' => '変更を保存',
	'html_quiz_dfl_button' => '初期値に戻す （設定を破棄）',
	'html_quiz_saved_message' => 'プラグインの設定を保存しました。',
	'html_quiz_reset_message' => 'プラグインの設定を初期値に戻しました。',
	'html_quiz_remove' => '削除',
);

/*
	Omit PHP closing tag to help avoid accidental output
*/