<?php
return array(
	'html_quiz_count_label' => 'Extra field count',
	'html_quiz_count_note' => '',
	'html_quiz_maxfile_size_label' => 'Max file size',
	'html_quiz_maxfile_size_note' => '',
	'html_quiz_only_image_label' => 'Permit only images (jpeg,png,gif)',
	'html_quiz_only_image_note' => '',
	'html_quiz_image_maxwidth_label' => 'Max image width',
	'html_quiz_image_maxwidth_note' => '',
	'html_quiz_image_maxheight_label' => 'Max image height',
	'html_quiz_image_maxheight_note' => '',
	'html_quiz_thumb_size_label' => 'Thumbnail width of attached image',
	'html_quiz_thumb_size_note' => '',
	'html_quiz_lightbox_effect_label' => 'Enable lightbox effect',
	'html_quiz_lightbox_effect_note' => '',
	'html_quiz_active_label' => '-------------------- Enable field^ --------------------',
	'html_quiz_prompt_label' => 'Label on question form:',
	'html_quiz_prompt_default' => 'field^',
	'html_quiz_prompt_note' => '',
	'html_quiz_prompt_error' => 'Input label on question form.',
	'html_quiz_note_label' => 'Explanation on question form - HTML allowed:',
	'html_quiz_note_note' => '',
	'html_quiz_type_label' => 'Type:',
	'html_quiz_type_text' => 'textbox',
	'html_quiz_type_textarea' => 'textarea',
	'html_quiz_type_checkbox' => 'checkbox',
	'html_quiz_type_select' => 'selectbox',
	'html_quiz_type_radio' => 'radiobutton',
	'html_quiz_type_file' => 'file',
	'html_quiz_type_note' => '',
	'html_quiz_option_label' => 'Options:',
	'html_quiz_option_default' => '',
	'html_quiz_option_note' => 'Textarea ex: 5 (this is rows)<BR/>Checkbox ex: OFF==0||ON==1 / NO==0||YES==1<BR/>Select/Radio ex: ||label1==value1||label2==value2||label3==value3<BR/>File ex:Combine allowed file extensions by comma(,)<BR/>Program ex: @EVAL return \'||label1==value1||label2==value2\';',
	'html_quiz_option_error' => 'Textarea ex: 5 (this is rows)<BR/>Checkbox ex: OFF==0||ON==1 / NO==0||YES==1<BR/>Select/Radio ex: ||label1==value1||label2==value2||label3==value3<BR/>File ex:Combine allowed file extensions by comma(,)<BR/>Program ex: @EVAL return \'||label1==value1||label2==value2\';',
	'html_quiz_option_ext_error' => 'Only ^ file types are allowed.',
	'html_quiz_attr_label' => 'Attributes:',
	'html_quiz_attr_note' => 'Note: Other attributes of input tag in accordance with rule of HTML.<BR/>Textbox ex: maxlength="20"<BR/>Select ex: size="3"',
	'html_quiz_default_label' => 'Default value:',
	'html_quiz_default_default' => '',
	'html_quiz_default_note' => '',
	'html_quiz_form_pos_label' => 'Position on question form:',
	'html_quiz_form_pos_top' => 'Top',
	'html_quiz_form_pos_custom' => 'Below custom text',
	'html_quiz_form_pos_title' => 'Below title',
	'html_quiz_form_pos_category' => 'Below category',
	'html_quiz_form_pos_content' => 'Below content',
	'html_quiz_form_pos_extra' => 'Below extra field of Q2A',
	'html_quiz_form_pos_tags' => 'Below tags',
	'html_quiz_form_pos_notify' => 'Below notify',
	'html_quiz_form_pos_bottom' => 'Bottom',
	'html_quiz_form_pos_note' => '',
	'html_quiz_display_label' => 'Show on question page',
	'html_quiz_display_note' => '',
	'html_quiz_label_label' => 'Label on question page:',
	'html_quiz_label_default' => 'field^',
	'html_quiz_label_note' => '',
	'html_quiz_label_error' => 'Input label on question page.',
	'html_quiz_page_pos_label' => 'Position on question page:',
	'html_quiz_page_pos_upper' => 'Upper content',
	'html_quiz_page_pos_inside' => 'Inside content',
	'html_quiz_page_pos_below' => 'Below content',
	'html_quiz_page_pos_note' => 'When you chose "Inside content", explain on "Explanation on question form" that Asker has to include tag( ^ ) in contents.',
	'html_quiz_hide_blank_label' => 'Hide on question page if blank',
	'html_quiz_hide_blank_note' => '',
	'html_quiz_required_label' => 'Input is required',
	'html_quiz_required_note' => '',
	'html_quiz_required_message' => 'Please enter something in "^".<BR/>',
	'html_quiz_save_button' => 'Save Changes',
	'html_quiz_dfl_button' => 'Reset Defaults (Discard Settings)',
	'html_quiz_saved_message' => 'Plugin settings saved',
	'html_quiz_reset_message' => 'Plugin settings reset',
	'html_quiz_remove' => 'remove',
);

/*
	Omit PHP closing tag to help avoid accidental output
*/